language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
env:
  global:
  - PROJECT_NAME: LD33
  - GH_REF: github.com/$TRAVIS_REPO_SLUG.git
  - secure: "LZSoSyck4D/iipWs/1yRBy1eFkhuWBr4ct36UZRQY76yNkke0grELmHGD8m8UCW3RrgB0o4MsMuhAxV+aux5iZmihaXg8g1hhpbQ2sritM9ZoZmiAejMLt9Ji+sXPJQ8aIiFRlbNP0mzPF5n1GtaHmSS70Nc4JrSEVbDaPRcq5OBrjQi4HqxQ8HL602wnzrlrAXdyd2IBRdBkKmp+FZJSyD9NnQxg68i3/H0fr+RrI2rBjhLcti660I9XBC9iPqsDkgfeEVppdNkbqGPg/ka2qCTMkdPDE8HiA0rDk1AI09eVVLYCbzjpe6D14O9X9ARPUwVJ5Q0A6uz+6tw0YDRlA+6HCPD2BJvXn/9OvBmT0FXP3y6Wo/IGD6g6ergyhOFTKwZnPj1fs+sbcYahR7TEnWYvv9E3BWQBTFjSx8crpV7StKqkvLT/cXtNVIAb5GqAKCiY7tSab0BOO8Idnr3KeL63SXlZfUJenJLCd7cLzDyXU0sPrzSQuZv/JOSsGRilwY1slSskQyU9AXCeZjke+MbHeHbC1Ium/McbBUg9immF5wgcF2s3224ZUb0ZiF+m6fw0kZ8p9Zw2u/RSyhNrutEJtvULC5w/mQfVem1pwKw8qTpLPsvxbu2bq4/PsS9uZOA98L3u9jEhW9pmrXTb0LIbZOnjxaZVDO85feQ31E="
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
- ./Scripts/tag.sh
before_deploy: 
deploy:
  provider: releases
  api_key:
    secure: AC+uJqZffPIZyOennEaveZQJsatOqaOByeAXuf5gDedf360dMdRA4ffxJRarhTWM9lU4eAMAvL9DfM7qG5twKxXdB2+VyT3TjY3yyYHd5YrdxLXQS7Avi150v/rEmZrbQR0qCUMa3njvluEc10Scx+DyqQLBSH3vEdW5KxwvAH+oeA7BtKG0tZUHbIPhp1Uho1Z4FXN0Du18QCwX+eqGLBrFfy5r4ckmzskOVdGXEGhKRbuYO8tqSzlyfNCm33jztqcXrokF8DjO+dLzRaaYba5PP+WWqx5UYg4v3l0NE3Zi+xHWoIR/wvuzvgX/5uNqIRmWaQ0w/UrdSOAk33Hv/s7BsweH00IwP2moj7QvQPCeupGUD0JLY+eW0SZL0sLAyywwcFtQk7l7c+AjCADl+mFxFST0pf1CMhlVas0d7Rkli8h7njDGU0ag2gICARYu9CZgI9/8y4i5/2Kv4NiqI7UQVbQw/2FFO9Iu2O0V90RBfhhYUSdM/AJ8nMK40FgPw0uachsYFbzj5h7bP5p/1zHPZED71PEe1G+yDoBrG09/z5w4WPyBT4zOQ2w08lfzXvaJbP6go8Sfbsr8M96odoLHueOK6mVhghgNNRzxYcklwXokqm97k2ji87wXh2vZhUlk7Fg5NIW+pp9Oj5V1kqgEbzxZR6D5M0q/KpDvRBI=
  file:
  - ./Build/osx_$TRAVIS_BRANCH-v0.$TRAVIS_BUILD_NUMBER.zip
  - ./Build/linux_$TRAVIS_BRANCH-v0.$TRAVIS_BUILD_NUMBER.zip
  - ./Build/windows_$TRAVIS_BRANCH-v0.$TRAVIS_BUILD_NUMBER.zip
  on:
    repo: cor/LD33
  skip_cleanup: 
after_deploy: true
- ./Scripts/deploy-ghpages.sh
branches:
  except:
  - gh-pages
  - /^*-v[0-9]/
